### ISSUE TITLE
Any standards for code comments on LESS mixins?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/front-end#10]
Say you have a function in JavaScript:

```javascript
function nifty(thing) {
  return thing * 10000;
}
```

A javadoc-inspired code comment for that function would look like:

```javascript
// Does something nifty with thing.
// @param thing [Object] A boring toaster.
// @returns [Object] A hip, modern toaster.
function nifty(thing) {
  return thing * 10000;
}
```

Now take a Less mixin:

```less
.nifty( @thing ) { 
```

Is there an equivalent code comment style out there somewhere for Less mixins that documents the parameters for the mixin?

**Comment by jimmynotjim** [comment]
I've always followed [JSDoc](http://usejsdoc.org/) for comment blocks but `//` for inline comments with code hints in both JS and Less/Sass.

Ex.
```
/**
 * Does something nifty with things.
 * @param thing1 [Object] A boring toaster.
 * @param thing2 [Object] A boring oven.
 * @returns [Object] A hip, modern toaster oven.
*/
var nifty = function(thing1, thing2) {
  // If thing1 has an item use it, otherwise check thing2
  var item = ( thing1.item ) ? thing1.item : thing2.item;

  return item;
};
```

I have no set preference for Less or JS, but in an attempt to make things simpler I'd suggest we use one style for both file types. I only fell on JSDoc because most of the OSS world seems to use it.

**Comment by ascott1** [comment]
In our [Less general practices](https://github.com/cfpb/front-end/blob/master/css.md#less-general-practices) we have:

> Put comments in // statements

Should this be more explicit to cover block comments?

**Comment by anselmbradford** [comment]
Single line `//` is fine, but I was wondering if there's any convention around the actual structure of the comment. If there isn't, following JSDoc sounds like a logical approach, per Jimmy's comment.

**Comment by ascott1** [comment]
I agree that following JSDoc sounds like it makes sense. We should add some documentation to the standard calling this out.
