### ISSUE TITLE
Using npm run build

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/front-end#101]
I was [catching up on CF stuff today](https://github.com/cfpb/capital-framework/pull/258#discussion_r48776849) when I noticed @contolini used `npm run build` to future proof against changing our build tools. 

I love the idea and want to know how other people feel about it. Is it overkill with `setup.sh`? Do you never see some projects moving off grunt and think it's unnecessary? Or should we add this to our standards?

**Comment by contolini** [comment]
:+1:

**Comment by awolfe76** [comment]
Interesting. I saw this the other day - http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/ - and it seems like something to try. (In case you miss his link at the top, the article comes from his other post - http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/)

Was going to talk to @wpears about trying some of this for some upcoming HMDA projects.

**Comment by Scotchester** [comment]
@contolini What are you :+1:ing?

@KimberlyMunoz:

> Is it overkill with setup.sh?

How do you mean?

---

I think we've already informally made the decision to move toward Gulp going forward, and several projects are already using it. But we will probably need to support Grunt for some time, as migrating a Grunt project is definitely not trivial. I am in favor of setting the standard build command as `npm run build`, so we can continue to support multiple build tools as long as we need to.

**Comment by contolini** [comment]
To clarify: I support recommending `npm run build`. I don't think it's overkill.

In personal projects I tend to not use grunt/gulp at all and simply use npm scripts as described in @awolfe76's link. I'm not suggesting CFPB projects stop using grunt/gulp -- just emphasizing that a project's build command should be build tool agnostic.

**Comment by KimberlyMunoz** [comment]
> Is it overkill with setup.sh?

`setup.sh` or `frontendsetup.sh` were established to help us be more build-tool agnostic to initially setup a project. I wanted to make sure no one thought that here since `setup.sh` does additional clean up steps and can take longer to run than whatever is contained in `npm run build`. 

I'm in favor, but want to make sure that people have a chance to say their piece and raise any potential objections.

**Comment by ascott1** [comment]
:+1: to this idea too

`setup.sh` could run `npm build` to be build tool agnostic. It just knows it has to build front-end assets. I feel like that would aid in BEWD integrations too (at least by creating consistency).

**Comment by Scotchester** [comment]
At the CF meeting on 1/15/16, we agreed to standardize on this.

`setup.sh` scripts can be updated to run `npm run build` instead of `grunt build` or `gulp build` if desired, but developers should standardize on `npm run build` when working with their projects.

See: cfpb/generator-cf#12

**Comment by anselmbradford** [comment]
Note that V1 now has a further abstraction on `setup.sh` in that it runs `frontend.sh` and `backend.sh`, respectively. That won't impact this I don't think, other than for this update to land in V1 it'd be updated in `frontend.sh` and not `setup.sh` directly.
