### ISSUE TITLE
Microformats vs Schema

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/front-end#11]
We started a discussion on [Microformats](http://microformats.org) vs [Schema](http://schema.org) over in [cfgov-refresh#258](https://github.com/cfpb/cfgov-refresh/pull/258). It seemed like a larger discussion than we should be having on that PR so I'm bringing it over here.

## First, why do we care?

As web pages become increasingly complex, people (read search engines) have attempted to create micro data to make page content easier to parse and index. Microformats was one of the earliest, and it's seen quite a few changes in the last ten-ish years. Schema is the newest, but it's also the one most of the search giants are leaning toward (especially Google).

## My Views

I've used both. Microformats is far less invasive to your code base (class name based) and I think much easier to grok. Schema requires a lot of new attributes that most people don't easily understand without using it and you really have to think about how the parts of your page fit together.

Working for an SEO driven shop for the past three years I see the benefit (and downsides) to both. That said, in our very un-scientific experience, Schema seemed to have a better return in both search rankings *and* user intent (the later is almost more important than the former). If this is our goal I suggest Schema.

## Tools

There's a couple of Chrome extensions I've used to make validating my micro data easier. Neither is fancy or visually appealing but they do the job.

### Microformats

- https://chrome.google.com/webstore/detail/microformats/oalbifknmclbnmjlljdemhjjlkmppjjl?hl=en

### Schema

- https://chrome.google.com/webstore/detail/semantic-inspector/jobakbebljifplmcapcooffdbdmfdbjh?hl=en

## Examples (all I could find were schema examples)

After installing those extensions you can navigate to any page in chrome and if it's using either format a small icon will appear in the address bar. Click the icon to expand the results.

- http://github.com - within users/orgs/repos
- http://youtube.com - within users/playlists/videos
- http://squarespace.com/
- http://www.bostonglobe.com/
- http://www.last.fm/music/Florence+%252B+the+Machine
- https://medium.com/

Now discuss! (or not, this is a democracy after all)

**Comment by KimberlyMunoz** [comment]
Adding screenshots for folks who don't want to install a chrome extension to see examples.

##Github
![image](https://cloud.githubusercontent.com/assets/1860176/6258714/eefde15a-b798-11e4-8bc8-7faf5196eee6.png)

## Boston Globe
![image](https://cloud.githubusercontent.com/assets/1860176/6258730/0eb65e28-b799-11e4-9f8c-14071e3f359d.png)
![image](https://cloud.githubusercontent.com/assets/1860176/6258738/1e0376ae-b799-11e4-8fc7-b6873ee7c3bd.png)

**Comment by KimberlyMunoz** [comment]
Unless there are folks already using microformats, I'd say it's better to go to where the standards will be.

Since there's so many different schema types, it might be good to give guidelines on the most common ones we'd encounter to promote consistency.

**Comment by jimmynotjim** [comment]
Good call on the screenshots, sorry I didn't include them. Here's the other ones.

## Youtube

![screen shot 2015-02-18 at 6 34 26 pm](https://cloud.githubusercontent.com/assets/1280430/6259085/d4ffd6ce-b79c-11e4-8769-3b55b4916e06.png)

## Squarespace

![screen shot 2015-02-18 at 6 35 15 pm](https://cloud.githubusercontent.com/assets/1280430/6259093/ea08d034-b79c-11e4-8ed9-2bcb7f8745ed.png)

## Medium

Turns out Medium is missing all their data besides the page title. I'm pretty sure the page content used to show up but ¯\_(ツ)_/¯. Going to guess it's related to Readability failing to parse their page content lately.

**Comment by jimmynotjim** [comment]
@davidakennedy, @Scotchester mentioned you had done a bit of research into Microformats/Schema while you were with the Fellowship. Do you know of any documentation we should consider? Did you come to a conclusion on which would be better for the Bureau?

**Comment by ascott1** [comment]
In the past, I've used Microformats, but after doing some reading this morning Schema seems like the better option. Based on all of the examples, it also seems to be used much more across the industry.

**Comment by ascott1** [comment]
Also @jimmynotjim, whichever direction we go, we should be sure to recommend the appropriate Chrome plugin in the style guide.

**Comment by davidakennedy** [comment]
Hi @jimmynotjim!

I only did about 90 minutes of research one day. I had been following the [Indie Web Camp](https://indiewebcamp.com/) movement, and found out the [Microformats had been updated recently](http://microformats.org/2014/06/20/microformats-org-turns-9-upgrade-to-microformats2).

Of the research I did, I was leaning toward Microformats. I couldn't find much that said one was way better than the other, and I liked how Microformats is less obtrusive on your markup. Also, I put a lot of weight behind the fact that WordPress Core uses Microformats (version 1), and many in the web standards community seem to prefer it.

My next step was going to be looking at large media sites or content heavy ones, and see what they used. I wanted to find some real-world examples. Most of what I had was rooted in personal feelings rather than objective research. :smile:

Hope that helps!

**Comment by anselmbradford** [comment]
Seems relevant to note here that [cfgov-refresh](https://github.com/cfpb/cfgov-refresh/blob/gh-pages/blog/_single.html#L17) also includes some [Open Graph support](http://ogp.me/).

**Comment by jimmynotjim** [comment]
@davidakennedy it does, thanks for taking the time to reply.

**Comment by jimmynotjim** [comment]
Open Graph (along with [Twitter Cards](https://dev.twitter.com/cards/overview)) is great for when content is shared, FB, Slack, Pinterest, etc all use it to pre-populate previews but Google (including G+) doesn't. I'd say it's worth supporting both of the OG and Cards (they're essentially just new meta-tags), but probably best to pick one micro-format.

Google has a [Schema overview](https://support.google.com/webmasters/answer/1211158) that's worth referencing as well.

**Comment by anselmbradford** [comment]
Another thing worth noting is schema.org includes metadata for [government services](http://schema.org/GovernmentService) ... I'm not sure if there is a microformat equivalent.

**Comment by jimmynotjim** [comment]
After a few more discussions it seems we have come to a consensus to use Schema. @KimberlyMunoz and I will be sure to include details about Schema in the template/markup standards.
