### ISSUE TITLE
Shared cf.gov templates

### ISSUE THREAD

**Issue by ascott1** [cfpb/front-end#12]
As we transition to cf.gov-refresh, we are also building new tools that will live at cf.gov. While Capital Framework does an excellent job of providing us with shared styles and patterns, we run the risk of having individual templates across a range of projects. 

For example, if a change is made to the styles of the cf.gov-refresh sidebar nav, we will need to update that change in multiple places. The difficulty of that change could vary wildly in each case, since the markup and styles are not the same.

**How can we make sure that our templates stay in sync across projects?**

One potential solution would be to have a separate repo that each of our projects pulls in as a dependency (with Bower or npm). This repo would contain base templates and layouts, ensuring that our sites stay in sync. Making a change to a project would be as simple as bumping a dependency #.

Thoughts? Other ideas?

**Comment by cfarm** [comment]
Following up on your Bower dependency suggestion, looks easy enough to create a Bower package we could pull in for our projects based on Capital Framework. http://bower.io/docs/creating-packages/

We can do this with private repos too if needed: http://www.frontendjunkie.com/2014/01/using-bower-as-package-management-tool.html

**Comment by jimmynotjim** [comment]
Flap Jack currently pulls in Capital Framework as if it were private
https://github.com/cfpb/cfgov-refresh/blob/gh-pages/bower.json#L23-L30

Should we add this task to the markup/templates standards group work? We could use these reusable modules as a baseline for writing the standards and then publish to bower when we're done.

**Comment by cfarm** [comment]
Yes.

What about adding just one Capital Framework dependency instead of the list of all the separate repos? You're missing typography for instance, and new CF repos would have to be added manually to the bower.json file. It'd be hard to keep track of what's new and available for us to use for those of us who aren't on Flapjack.

You should also make recommendations around contributing, so current CF.gov projects can make updates to CF to use in our sites. Does Flapjack team have standards for this already?

**Comment by anselmbradford** [comment]
> What about adding just one Capital Framework dependency instead of the list of all the separate repos?

There needs to be the option to only load components of CF so an enormous dump of unused components isn't pulled in when only a piece is needed. But the idea of having a root-level CF import that pulls in the latest of everything is appealing. I'm not sure if this exists already. It may be applicable only to FlapJack to do it that way though, as FlapJack would include all components used site-wide, while subsections of FlapJack likely wouldn't use everything.

> You should also make recommendations around contributing, so current CF.gov projects can make updates to CF to use in our sites. Does Flapjack team have standards for this already?

There's this --> http://cfpb.github.io/capital-framework/contributing/

**Comment by cfarm** [comment]
I think other projects might want to use the 'all-components' package as well, but I see what you're saying. 

Short-term, the component approach would be awesome to implement on Owning a Home, we just need documentation on how to do it :)

**Comment by ascott1** [comment]
[This is a thing that's happening](https://github.com/cfpb/cfgov-sheer-templates). Are projects using these?

**Comment by Scotchester** [comment]
Yes! Currently in real-live use on [ghe]/CFGOV/fin-ed-resources. Also in development on [ghe]/CFGOV/know-before-you-owe

**Comment by ascott1** [comment]
Yay! Let's continue advocating for the use of these templates as much as possible. Nice work @Scotchester!
