### ISSUE TITLE
Markup and template standards

### ISSUE THREAD

**Issue by ascott1** [cfpb/front-end#2]
Let's use this issue to discuss markup and template standards as we work towards building our own style guide.

To kick off the discussion, here are some markup style guides:

- [Github](https://github.com/styleguide/templates)
- [@mdo's Code Guide](http://codeguide.co/#html-syntax)
- [Google](http://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml)
- [ThinkUp](https://github.com/ThinkUpLLC/ThinkUp/wiki/Code-Style-Guide:-HTML)

**Comment by KimberlyMunoz** [comment]
I'm thinking of taking our existing standards and making edits to include examples and a couple other things like:

- Templates based on Capital Framework
- Guidelines on [using HTML5 specific elements](https://github.com/ThinkUpLLC/ThinkUp/wiki/Code-Style-Guide:-HTML#permitted-elements) - They will help with accessibility down the line and seem to be used with a HTML5 in Bureau already.
- Accessibility tags
- Patterns for forms and tables.

**Comment by jimmynotjim** [comment]
There's also 

- [Isobar](http://isobar-idev.github.io/code-standards/#_markup)
- [Gov.uk Accessibility Standard](https://www.gov.uk/service-manual/user-centred-design/accessibility)

**Comment by ascott1** [comment]
I like where this is going.

**Comment by KimberlyMunoz** [comment]
+ A11yProject has [an accessibility markup checklist](http://a11yproject.com/checklist.html) we should be checking for in our projects
+ [Its Tired in Here's guide](http://itstiredinhere.com/accessibility/) is pretty insightful on how that additional markup works.

**Comment by jimmynotjim** [comment]
Two more good accessibility checklists from WebAIM

- http://webaim.org/standards/wcag/checklist
- http://webaim.org/standards/508/checklist

**Comment by jimmynotjim** [comment]
Mashed up all the above markup guidelines/standards. I included everything that wasn't a duplication-whether I agreed or not-to leave it open to debate.

https://gist.github.com/jimmynotjim/4122de4166d51668b066

**Comment by ascott1** [comment]
That is excellent @jimmynotjim.

**Comment by KimberlyMunoz** [comment]
I made a new branch for team-markup changes.

https://github.com/cfpb/front-end/blob/team-markup/markup.md

:sparkles: Go team-markup! :sparkles:

**Comment by cfarm** [comment]
There's a grunt task that will validate your HTML: https://www.npmjs.com/package/grunt-html-validation worth a try.

**Comment by jimmynotjim** [comment]
Ben Balter released a new automated accessibility testing suite (in Ruby) the other day https://github.com/benbalter/ra11y. Might be something to look at cloning in Python.

**Comment by KimberlyMunoz** [comment]
I noticed [grunt-html-validation](https://github.com/praveenvijayan/grunt-html-validation/issues) actually sends stuff to the w3c validator instead of validating locally and that causes some issues. I'm going to look into [grunt-html](https://www.npmjs.com/package/grunt-html), which has more downloads.

**Comment by anselmbradford** [comment]
Any thoughts on using http://jade-lang.com/ ?

**Comment by Scotchester** [comment]
@anselmbradford I have a pretty visceral negative reaction to it, but it's just that -- visceral, and not based on any particular logic or reasoning. What would be the benefits of it?

**Comment by anselmbradford** [comment]
I haven't used jade, but I have used haml a lot, which is conceptual equivalent. I HATED it when I started. I didn't see the point of markup for markup. Then I realized it standardizes silly things like spacing discrepancies between contributors, mis-nested elements, and missing ending tags—making PRs like https://github.com/cfpb/cfgov-refresh/pull/445/files#diff-83d225d022799caf178d5ae589f26403R31 not necessary. 

I... I... kind of miss it.

**Comment by KimberlyMunoz** [comment]
So I just saw a website that uses Jade and partials and it was nice and straightforward. There's basically no style guide to worry about when contributing.

But I don't think it's worth including in the standards until someone else has thoroughly tested it for all the edge cases and we know it will stick around. Luckily, we can always come back and edit these if things change.

**Comment by ascott1** [comment]
Now that the initial standard is in the master branch, let's close this issue and move further discussion and edits to new issues.
