### ISSUE TITLE
node

### ISSUE THREAD

**Issue by wpears** [cfpb/front-end#25]
:grey_exclamation:Howdy front-enders:grey_exclamation: 

So we haven't really talked about node much, which might be the right thing to do--it isn't strictly a front-end topic (an aside: if you are a front-ender and need your first draught of node, check out the [art of node](https://github.com/maxogden/art-of-node)).

That said, many of the tools we use are built on top of node (all of our commonly used build tools and package managers) and so I think we should have a keen interest in getting our node stuff right as we extend/enhance these tools.

Also, with tools like [browserify](http://browserify.org/), modules written in node (and managed by npm) can be dropped into the front-end quite easily and so are well within our purview, imo.

So!

Our existing JS standards should translate pretty decently to nodeland, but I think we'd be well-served with some words on "the node way" or generally keeping things modular and automating processes as much as is reasonable ([an example of this in the context of testing](http://substack.net/how_I_write_tests_for_node_and_the_browser)). I'd also encourage people to publish reusable modules to npm whenever possible, which is strongly in line with our open-source-by-default ethos.

Writing modular code could very well be pulled into its own topic that transcends us front-enders, but since node is so steeped in this approach, if nothing else it could be a good vehicle to launch the discussion. :rocket:

**Comment by ascott1** [comment]
> I'd also encourage people to publish reusable modules to npm whenever possible, which is strongly in line with our open-source-by-default ethos.

:heavy_plus_sign: :100: 

I think we should be doing this as much as we can with our projects. For example, I'm really interested in us publishing more financial node modules similar to [amortize](https://www.npmjs.com/package/amortize).

**Comment by anselmbradford** [comment]
> ... more financial node modules similar to amortize.

Hey, I recognize some of those collaborators!

**Comment by ascott1** [comment]
Also, if we're publishing modules to npm we should list [CFPB](https://www.npmjs.com/~cfpb) as a collaborator. We've also traditionally added a few CFPB employees as well.

This is the sort of thing that would be really useful in a node guide. :stuck_out_tongue_winking_eye:

**Comment by ascott1** [comment]
I added a first pass at an npm guide in pull #26. It's not perfect, but documents our current process.

**Comment by ascott1** [comment]
@wpears do you think we've resolved this with the npm guide? Should we add additional guidelines or documentation?

**Comment by wpears** [comment]
Resolved, thanks again for the work on #26, Adam :cake:
