### ISSUE TITLE
Project Organization

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/front-end#28]
I'm in the middle of a re-organizing `cfgov-refresh` to use the src / dist layout but have a question for the team. What exactly should be included in `/src`? 

My original plan was to only store [files that were compiled](https://github.com/cfpb/cfgov-refresh/tree/project-standardize/src/static) in `/src`. This is how I've generally organized larger site [projects in the past](https://github.com/jimmynotjim/dxboston.com/tree/public/web/wp-content/themes/dbcom-theme/assets). @Scotchester brought up a good point though. Many developers think of the `/dist` as _the_ set of files needed to run the site and this is how I typically organize [smaller projects and libraries](https://github.com/jimmynotjim/scrollNav).

Are there opinions on one vs the other? Originally I was against keeping everything in `/src` because that would mean even longer grunt processing while every file is transferred from one location to the other, but it does make sense to keep all the files for actually running the site together. Do we have any examples of projects of this size other than [Owning a Home](https://github.com/cfpb/owning-a-home) (which keeps everything in `/src`)?

**Comment by ascott1** [comment]
I think, I lean towards what @Scotchester is saying.

From <https://[ghe]/pages/CFPB/dev-manual/front-end-build.html>, which should probably be moved here:

> You should avoid checking dependencies and minified assets into source control. It’s common practice to keep source files in a src directory and compiled/minified assets in a dist directory.

**Comment by jimmynotjim** [comment]
I looked at that page but it doesn't clarify what a source file is. The "compiled/minified assets" implies a source file is only the assets that will be compiled (typically css and js), but as @Scotchester brought up, many devs consider `/dist` to be the distributable source, that there shouldn't be any files required to run the site outside of it. 

My main argument is that there's no reason to put non-compiled files in the `/src` directory because there's nothing being processed and you end up wasting time [copying those files](https://github.com/cfpb/owning-a-home/blob/master/Gruntfile.js#L272-L335) during the build. You also have to [watch all those files](https://github.com/cfpb/owning-a-home/blob/master/Gruntfile.js#L458-L464) for changes which can seriously bog down development speed. 

I honestly don't know which is better right now, but for cfgov-refresh I'm wary to watch and copy every single file. Maybe I ought to set it up and compare build times?

**Comment by Scotchester** [comment]
The watch command shouldn't (and doesn't, in the case of what you linked to) watch images and fonts. It does watch HTML files, so that it can copy them to `/dist` if updated.

Does copy forcibly overwrite identical files? If not, the additional time is probably minimal.

All that said, if we as a group _don't_ take the view that `/dist` is the self-contained, distributable code, then I don't really see the point of `/dist`. Just leave everything in a static folder and ignore the compiled stuff (e.g., the current cfgov-refresh setup).

**Comment by jimmynotjim** [comment]
grunt-contrib-copy replaces everything which is why I'm a bit against it. I've found [grunt-copy-changed](https://github.com/qsat/grunt-copy-changed) which does what it says and is at least worth testing. Going to give that a shot in project-standardize branch and see how it goes.

**Comment by jimmynotjim** [comment]
I copied OAH's setup and got everything working, and it turns out `grunt-contrib-copy` is actually much faster than I expected. Here's the output when running grunt to move everything from `/src` to `/dist`

```
Execution Time (2015-04-10 19:38:09 UTC)
less:main               2.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 56%
autoprefixer:main      187ms  ▇▇▇▇ 4%
legacssy:ie-alternate   66ms  ▇▇ 1%
uglify:js               1.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 36%
copy:main              123ms  ▇▇▇ 2%
Total 5.2s
```

Looks like performance wise we have a lot more to worry about with our css and js compilations.  Unless anyone else speaks up, I'm going to continue in this direction for cfgov-refresh in hopes of this going live within the next two weeks.

**Comment by jimmynotjim** [comment]
Looking good so far on cfgov-refresh. Going to go ahead and close this out
