### ISSUE TITLE
CSS/LESS standards

### ISSUE THREAD

**Issue by ascott1** [cfpb/front-end#3]
Let's use this issue to broadly discuss CSS and LESS standards as we work towards building our own style guide.

To kick off the discussion, here are some example CSS style guides:

- [Github](https://github.com/styleguide/css)
- [Google](http://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml)
- [@mdo](http://codeguide.co/#css)
- [Idiomatic CSS](https://github.com/necolas/idiomatic-css)
- [cssguidelin.es](http://cssguidelin.es/)
- [ThinkUp](https://github.com/ThinkUpLLC/ThinkUp/wiki/Code-Style-Guide:-CSS)
- [Mapbox](https://www.mapbox.com/base/styling/)

Are there guides that you particularly like?

**Comment by awolfe76** [comment]
This is great!

Any thoughts on using bits of each? Maybe breaking down specific sections:
- tabs vs spaces (Oh, no. Not right off the bat.)
- closing braces placement
- white space
- declaration order
- etc

Might be easier to work out our own that way.

**Comment by awolfe76** [comment]
Oh, and not to bring up a whole other topic, but ... LESS vs Sass?
Maybe a little background on why you guys took the LESS route for the CF.

I've used Sass quite a bit in the past and now that Jekyll, which we seem to use a lot too, has Sass built in. (All while understanding that this would be a huge change at the moment.)

**Comment by jimmynotjim** [comment]
I've always gone by [thoughtbot's guides](https://github.com/thoughtbot/guides), worth reading through all of them, especially the [Code Review](https://github.com/thoughtbot/guides/tree/master/code-review) one.

**Comment by ascott1** [comment]
That code review guide is fantastic @jimmynotjim.

**Comment by mistergone** [comment]
I advocate that you guys all come up with something easy for me to follow, because I don't really care too much (and writing CSS is currently my least favorite part of front-end development :rocket: :rocket: :palm_tree:).

**Comment by jimmynotjim** [comment]
My only hard rules are targeting as directly as possible, limiting nesting to three levels (aside from pseudo classes), grouping layout and visual properties separately, and sorting properties by alpha (I know this one can be contentious).

**Comment by jimmynotjim** [comment]
Just saw this over the weekend [Trello CSS Guide](https://gist.github.com/bobbygrace/9e961e8982f42eb91b80)

**Comment by ascott1** [comment]
I really like this:

> You might get the impression from this guide that our CSS is in great shape. That is not the case. While we’ve always stuck to .js classes and often use namespaced-component-looking classes, there is a mishmash of styles and patterns throughout. That’s okay. Going forward, you should rewrite sections according to these rules. Leave the place nicer than you found it.

**Comment by jimmynotjim** [comment]
@ascott1 Yeah, I'm all for slowly upgrading a project over trying to fix everything and burning out in the process. It also alleviates everyone of any guilt/pressure when they don't have the time or resources.

**Comment by cfarm** [comment]
@Scotchester I'm going to take a stab at creating more specific examples of our CSS naming conventions, based on this here doc http://cfpb.github.io/capital-framework/contributing/#follow-our-css-naming-conventions

Can also write a standard about property order, since that doesn't seem to be established at all, and we have some good examples/ideas in this thread.

**Comment by Scotchester** [comment]
:+1:

It is established, actually :) Here's what we have to work with: https://github.cfpb.gov/pages/CFPB/dev-manual/css.html

I started a Wiki page here for any notes we might want to take along the way: https://github.com/cfpb/front-end/wiki/CSS-and-Less-Standards

(The final document should be an MD file in the repo, I think. Right, @ascott1?)

**Comment by cfarm** [comment]
Groovy, thanks.

**Comment by ascott1** [comment]
> The final document should be an MD file in the repo, I think. Right, @ascott1?

Yes, please. We'll eventually turn this into a proper Jekyll site.

**Comment by cfarm** [comment]
@Scotchester So we are using BEM conventions for naming classes. What do you think about making it easier to select a class name in a text editor by using only underscores and no hyphens?

With both underscores and hyphen for modifer:
![screen shot 2015-02-19 at 1 01 25 pm](https://cloud.githubusercontent.com/assets/702526/6272789/683315e6-b838-11e4-9e9e-2d27202bc074.png)

With only underscores:
![screen shot 2015-02-19 at 1 01 19 pm](https://cloud.githubusercontent.com/assets/702526/6272783/5ef97c54-b838-11e4-8b1b-efc212033e34.png)

This is a pretty minor improvement that might make coding faster, but would affect quite a lot of existing codebase.. but I thought I'd mention it anyway :) It could also be argued that having the modifier separately selectable is useful although I rarely find that to be the case.

**Comment by Scotchester** [comment]
During the original BEM discussion we did discuss this selectability issue and could find no good solution for it, other than users modifying their editor settings.

The issue with your suggestion is that now it appears that `block` with modifier `border` has an element `bottom`. We can't allow the element prefix to be a legal character within a modifier name.

I think we also considered camelCase instead of hyphenation for multi-word names, but decided the readability of hyphens was more important than the selectability.

**Comment by ascott1** [comment]
Where do we sit on this @Scotchester @cfarm?

**Comment by Scotchester** [comment]
Unfortunately, I don't think we'll have a draft together in time for today's meeting (unless Cat is working on one in secret.)

**Comment by ascott1** [comment]
Cool. Let's review what we've got and talk about a path forward.

**Comment by cfarm** [comment]
Here's what we've discussed so far mind-dumped into the wiki: https://github.com/cfpb/front-end/wiki/CSS-and-Less-Standards

**Comment by anselmbradford** [comment]
What do you'll think about the value of including the (keyword) in import statements? E. g.:

```
@import "style.css"
```

vs 

```
@import (css) "style.css"
```

The Less docs convention appears to be to [exclude the file extension when importing Less, but include it when importing CSS](http://lesscss.org/features/#features-overview-feature-importing):

```
@import "library"; // library.less
@import "typo.css";
```

Using the (keyword) syntax Less/CSS files will be treated like they are one type or the other, no matter what the file actually is: http://lesscss.org/features/#import-options

I don't have a strong preference either way, but thought I'd point out what the Less docs are doing.

**Comment by Scotchester** [comment]
I definitely prefer the explicitness of having the file extension, even for Less files, but I think the `(keyword)` should only be used when necessary. (See https://github.com/cfpb/owning-a-home/pull/368/files#r25871443 – still trying to remember why we did that)

**Comment by awolfe76** [comment]
You've probably seen this but just in case -
https://speakerdeck.com/mdo/at-mdo-ular-css

I agree with him on almost everything; single hyphens, naming conventions, would be great to have a linter and validator, and most of all simplicity ... everywhere! Starting simple you can always add what's needed but going the other direction is a nightmare.

The one thing I don't do is the way he orders properties. I've tried different ordering but seem to always have to look up where things are supposed to go.

> Where do box model properties go? First, second, third?
> - me

Personally I use straight alpha with a few exceptions:
- `min-` and `max-` properties, I put those with the width and height
- prefixes (yes, autoprefixer is great too)

Sorry I'm late to the game. :disappointed:

**Comment by jimmynotjim** [comment]
Really great article on building quality CSS at scale 

http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/

Some of it we're already using, but I wouldn't mind seeing us follow the o- and c- methods as well for easier identification. Right now I'm finding using cmd+shift+f an awful lot to see where class names are used in projects.

**Comment by ascott1** [comment]
I really like the simplicity of this CSS guide: <https://github.com/bevacqua/css>

**Comment by awolfe76** [comment]
I like that one too @ascott1, pretty straightforward.

**Comment by ascott1** [comment]
Now that the initial standard is in the master branch, let's close this issue and move further discussion and edits to new issues.
