### ISSUE TITLE
Project on-boarding guide

### ISSUE THREAD

**Issue by ascott1** [cfpb/front-end#32]
@anselmbradford recommended that there be a project on-boarding guide for each project.

@cfarm then suggested that we create a checklist of "needed documentation" for a project, that should be posted in a single place and easy to find.

Am I missing anything?

What should this checklist include?

**Comment by ascott1** [comment]
@contolini has a draft of a list. Let's review it and move it to the open

**Comment by anselmbradford** [comment]
Perhaps include in https://github.com/cfpb/open-source-project-template

**Comment by ascott1** [comment]
I recommend closing this in favor of this work being done by a broader discipline group (such as SWAG or Scrum CoP)

**Comment by Scotchester** [comment]
:+1: to the recommended closure
