### ISSUE TITLE
Code review guide

### ISSUE THREAD

**Issue by ascott1** [cfpb/front-end#33]
What constitutes a good code review?

**Comment by jimmynotjim** [comment]
I'll take this one on, I've had a few resources saved that I've been meaning to put together into a guide.

**Comment by ascott1** [comment]
:+1: nice!

**Comment by anselmbradford** [comment]
This might be a place to add some instructions on checking out a branch for review. Does everyone know how to do that? Maybe not.

For the [shared repository model](https://help.github.com/articles/using-pull-requests/#shared-repository-model) I use:

```bash
git checkout --track origin/branch-name
```

**Comment by jimmynotjim** [comment]
You can simplify this with `git fetch && git checkout branch-name`. When git fetches, it'll grab and track all branches from origin, even ones you don't have locally.

**Comment by anselmbradford** [comment]
So I just ran into this scenario. I had a project forked, then I went to the upsteam project and made an edit in the project using the GH UI editor (which automatically creates a patch branch). I tried `git fetch` locally and it didn't pull down that branch that GH created, but `git checkout --track …` did. Any idea why this would happen?

**Comment by anselmbradford** [comment]
Per discussion with @jimmynotjim, the issue was I didn't realize `git fetch` wouldn't show the remote branch name when running `git branch`, but it still can be checked out. All good!
