### ISSUE TITLE
JS testing guide

### ISSUE THREAD

**Issue by ascott1** [cfpb/front-end#34]
We have some internal documentation on unit testing - let's clean those up/modernize them and move them here.

**Comment by cfarm** [comment]
One thing I would really appreciate is some links to example tests in our codebase.

**Comment by cfarm** [comment]
* [ ] Add unit tests to the CF generator

**Comment by KimberlyMunoz** [comment]
We have a [guide to testing here](https://github.com/cfpb/front-end/blob/master/testing.md), we should look into what is possibly missing here.

**Comment by ascott1** [comment]
> We have a guide to testing here, we should look into what is possibly missing here.

Hey! Look at that! I hadn't seen that.

**Comment by ascott1** [comment]
I'm closing this based on @contolini's testing guide above. Long term, I think we could take this even further into the realm of practical testing guidelines.
