### ISSUE TITLE
Merging PRs

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/front-end#36]
A question as to [who should be merging](https://github.com/cfpb/front-end/pull/35#discussion-diff-28355660) PRs came up in #35. The dev manual says:

> __Don’t__: Merge your own pull requests!

But within Flapjack we've found there are a few good reasons to merge your own requests __after the appropriate number of sign-offs__ (we chose two reviewers)

- gives author a chance to cleanup and squash any edits (if desired);
- fix conflicts (sometimes there's a conflict, you fix it, then no one get's around to merging and new conflicts come up, creating a cycle of "please fix conflict" comments and related commits);
- merge when appropriate (sometimes multiple PRs need to go together).

In addition to this, merging our own PRs after being properly reviewed follows the bit about being trusted as a technology professional discussed in the Pain Points issue - https://[GHE]/sheltonw/2014-performance-kanban/issues/63#issuecomment-38650

**Comment by ascott1** [comment]
I think this is a conversation worth having, but one we should have with the team at large (not just the front-end team).

**Comment by mistergone** [comment]
Time travel! Almost four months later, I'll add that our Team decided to merge our own pull requests after requiring reviews. This puts the responsibility of getting a PR through on the person who made it, instead of a PR floating in space until someone decides to look at it. It means the Pull Requester has to get Teammates to review and comment so their code gets included.

**Comment by jimmynotjim** [comment]
Trend setters!! I think this is something we should really be bringing back up, and @ascott1 you're right it should be an org level discussion. Maybe we can schedule a conversation at the next Dev Cop after @virtix is back from leave? Or should we just start an internal issue in D&D?

**Comment by ascott1** [comment]
> Maybe we can schedule a conversation at the next Dev Cop after @virtix is back from leave? Or should we just start an internal issue in D&D?

I'd vote yes to both of these. Maybe start with the issue and set a hard deadline of "we're going to talk about and finalize this at the Dev CoP meeting on xx/xx/xx."

**Comment by jimmynotjim** [comment]
Opened an internal discussion in the handbook repo, issue 167 (sorry, no links)
