### ISSUE TITLE
Review checklist

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/front-end#38]
@anselmbradford mentioned we could include a checklist of items from the review guide to the PR template for often seen issues. Starting a list here but feel free to add to it (or open the PR adding them).

- Changes are limited to a single goal (no scope creep)
- Code can be automatically merged (no conflicts)
- Code follows the standards laid out in this playbook
- Passes all existing automated tests
- New functions include new tests
- New functions are documented (with a description, list of inputs, and expected output)
- Placeholder code is flagged
- Visually tested in supported browsers and devices
- Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- Have the assets/docs been built with grunt? (if applicable)

**Comment by ascott1** [comment]
This is in the review guide. Thanks @jimmynotjim!
