### ISSUE TITLE
JavaScript standards

### ISSUE THREAD

**Issue by ascott1** [cfpb/front-end#4]
Let's use this issue to broadly discuss JS standards as we work towards building our own style guide.

To kick off the discussion, here are some example JS style guides:

- [Idiomatic.js](https://github.com/rwaldron/idiomatic.js/)
- [airbnb](https://github.com/airbnb/javascript)
- [Google](http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml)
- [felixge's node style guide](https://github.com/felixge/node-style-guide)

**Comment by mistergone** [comment]
I like:
* Idiomatic's whitespace, type checking, conditional evaluation, and naming standards
* Consistent quotes. I can't decide if single-quotes or double-quotes is best to start with. As a note, I always want HTML tags to contain double-quotes, so one the occasion when I output HTML, I single-quote it... so, something like... `$("#pants").html('<a href="link">text</a>');` That might be an argument to use single-quotes by default. I go back and forth on this.
* Strongly avoiding ternary operators. I think they hurt code readability, and minifying code counteracts the advantage of ternary operators, anyway.


![Mmmmm](http://24.media.tumblr.com/tumblr_m8aogybWNM1rd51yyo1_500.gif)

**Comment by jimmynotjim** [comment]
- I like idiomatic as well (preferring spaces to conform with nearly every OSS library out there)
  - I strongly disagree on comma separating initialized vars ([safer to initialize each individually](https://github.com/jimmynotjim/training-roost/blob/master/javascript-fundamentals/javascript-fundamentals.js#L73-L83))
  - I dislike camelCase (underscores are so much easier to read) but I'll conform to what everyone has been using so far.
  - I don't feel as strongly about switch statements, it's not like we're building the entire front end in JS.
- I agree on using single quotes by default and saving double quotes for contained html attributes.
- I feel ternary is ok for shorter conditions/definitions rather than initializing a var and updating it within conditions but agree complex ternaries hurt readability.

**Comment by mistergone** [comment]
- I don't love or hate the "clean, comma separated" initalized vars thing. I don't think it's more readable (nor less readable), but sometimes it does end up looking ridiculous. And sometimes you just end up essentially "re-initializing" the variable later, so... Idiomatic likes it, I don't hate it, so I just go with it. :smile: 

- I no longer care about camelCase, underscores, or justonelongstring styles of vars and functions. Consistency would be nice, but mostly I use editor features to find instances of vars and functions, I can copy/paste and never have to actually type them out, etc. Usually, I disagree more with _what_ people name their vars and functions than _how_ they format that name.
 - I do think we should avoid dashes in function and variable names. :information_desk_person: :neckbeard:

**Comment by KimberlyMunoz** [comment]
So long as there's a good linter we can use Bureau-wide, I'm not too picky about the rules we go with here.

I like starting with something that focuses on readability [Node.Js Style Guide](https://github.com/felixge/node-style-guide) or Idiomatic and we can add more rules that emphasize performance as time goes by. Some of those Airbnb articles look great.

**Comment by sephcoster** [comment]
I have worked with the Idiomatic guide for awhile as I think that's quite readable and closer to my personal style - but I can be flexible :) 

I personally default to single quotes most of the time out of habit, so I prefer those in my javascript - also makes including quoted text easier. 

If I had to choose I'd prefer camelCase for variable names in JavaScript and like to save hyphens for css classes. Underscores could work too, but I'd prefer to keep them to mean something specific in the app that helps make it more readable.

Lately I've been instantiating comma separated variables, but I've also noticed it leads to more build mistakes because I forget commas or placing semicolons in the right spots. Coin flip as to how we want to do that.

For the above (case, quotes, and commas) I think the node guide keeps things pretty clean. Both Idiomatic and Node guides are in agreement on variable naming and quotes I think.

Typically for linting on CFPB projects we've used JSHint as part of the grunt build process - keeps you honest, though I would like to see a common set of flags so we're not using different standards of linting.

I would be interested to hear what people's thoughts are on code structure. For example: 
- OK to define functions after they're used if it makes the code more readable?
- Switch statements or objects preferred?
- Limit to one layer of nested Ifs (still sloppy) before separating an activity to a separate function?
- Function length warning signs - 20 lines? Testable? Max 3 params? Etc.

**Comment by ascott1** [comment]
I just added the [existing JavaScript](https://github.com/cfpb/front-end/wiki/JS-Standards) style guide to the wiki. This might be useful as a base document.

**Comment by ascott1** [comment]
I came across this [Meta Code Style Guide](http://speakingjs.com/es5/ch26.html) from *Speaking JS* today.

@mistergone will appreciate the "Don't Be Clever" section.

**Comment by ascott1** [comment]
Where do we sit on this @mistergone @anselmbradford @wpears?

**Comment by anselmbradford** [comment]
Sorry @ascott1 We need to do some more chatting about it! @mistergone @wpears I can carve out some time in about 30 min if you want to chat?

**Comment by ascott1** [comment]
No worries @anselmbradford, just didn't want this to get forgotten about!

**Comment by anselmbradford** [comment]
@wpears and I had a conversation around this and jotted down these thoughts:

  - **Readable code:** Readability of the code should be a core lens through which these discussions happen. That said, people all have different interpretations and requirements over what readability means, so...
  -  **Emphasize, but not require, official linter settings:** CFPB should provide an official standard jshintrc settings file, which CFPB projects **should** use, but are not _required_ to use.
  - **Projects should adhere to their chosen standard:** Whether a project uses the CFPB official standard or chooses to go its own way (and use custom JShint options, for instance), what should be required is that the project follow its own internal standards project-wide.
  - **An quick way to verify conformity would be cool:** Along the lines of the above, it would be awesome if there was a badge that repositories could display that they are "CFPB-standards compliant" if they use the official jshintrc file. We speculated briefly on how this might be done with the GitHub API.
  - **Coding conventions that fall outside of a linter should be documented:** There are coding conventions that a linter won't pick up (for example, I like to prefix variables/functions with an underscore if they won't be exposed outside of a JS module). These conventions should be captured in the standards document and serve as a reference to what these conventions mean.

**Comment by ascott1** [comment]
:heavy_plus_sign: :100:

**Comment by sephcoster** [comment]
:shipit: Those are awesome, pithy, and concise. If we went no further I think we'd still be in good shape. I'd be interested in helping with badging / linting.

**Comment by mistergone** [comment]
I'm happy to carve out time to discuss, but what @wpears and @anselmbradford came up with is phenomenal. We can dive into "readability" more, but this is a great set of guidelines.

@ascott1 - I did appreciate the "Don't Be Clever" section! :smile: :rocket: :camel:

**Comment by contolini** [comment]
:+1: I'd recommend codifying many of the recommendations into requirements that we can run automated checks against:

- Every project must have a linter config file (either .jshintrc or .eslintrc). This can stray from the official CFPB recommendations but it has to be documented in a config file.
- Every project must be automatically linted as part of its build process (e.g. create a Grunt task for it).
- Don't push any code that has linting errors (e.g. fail Travis and Jenkins builds with style errors).

> Coding conventions that fall outside of a linter should be documented.

Check out [ESLint](http://eslint.org/). It's AST-based so you can check against *a lot* of [style rules](http://eslint.org/docs/rules/) and if they don't support a rule, you can [write a plugin](http://eslint.org/docs/developer-guide/working-with-plugins.html) to enforce it. Here's a [sample .eslintrc](https://github.com/contolini/dash/blob/master/.eslintrc) we're using with dash.

People don't RTFM so I find it's best to favor code over documentation.

**Comment by wpears** [comment]
Agreed @contolini 

The reason we included that phrase is that it is easier to tell people to write down conventions than to tell them to use ESLint AND write their own plugins, even though that is ideal.

Saying everyone SHOULD use ESLint would be pretty cool, but seemed outside the scope of our hangout. I'm definitely in agreement that something like a pre-commit git hook (or grunt task) wouldn't be too hard of a sell and would definitely lead to cleaner code in repos.

**Comment by ascott1** [comment]
I agree that having a codified ESLint file is a good idea. Many of our projects already use JSHint, so converting and cleaning things up to match our recommendations should be a reasonably straight forward process.

**Comment by cjfont** [comment]
+1 for creating a ESLint file that will represent the consensus.

**Comment by mistergone** [comment]
I just want to :+1: the sentiments of an "official" linting file, with variations for folks who want to do something different (as long as they document it), and I like a git hook for it as well. I don't know anything about ESLint and such, but I'm ready to learn.

**Comment by ascott1** [comment]
I haven't played around with it much, but [this pull request](https://github.com/cfpb/regulations-site/pull/684/files) adds ESLint to eRegs. There will need to be a fair amount of cleaning up to match our standards once we've settled on them.

**Comment by Scotchester** [comment]
:+1: :+1: :+1: to the general direction of this thread.

**Comment by anselmbradford** [comment]
I'd add to this discussion to usejsdoc.org ... especially since ESLint has a rule for it http://eslint.org/docs/rules/valid-jsdoc.html

**Comment by ascott1** [comment]
+1 for JSDoc

**Comment by sebworks** [comment]
I would just add that I hope we can move in the direction of ES6 sooner rather than later. Tools like https://babeljs.io/ can help with that.  Would be nice if we could consider using TypeScript or AtScript as well. http://techcrunch.com/2015/03/05/microsoft-and-google-collaborate-on-typescript-hell-has-not-frozen-over-yet/

**Comment by wpears** [comment]
I'm warmer to the idea of using ES6 over other compile-to-JS options. In general, the smaller the project, the more free you are to experiment, but I think a flagship project done in TypeScript would attract some trouble. There's some organizational cost to experimentation in new devs having to learn syntax, etc which isn't always justified, even if the language is "better".

ES6 is a little bit different in that the changes are less drastic and it's where Javascript as a whole is moving, so I think it's both easier to grasp and easier to sell to devs joining the project.

**Comment by virginiacc** [comment]
Just wanted to say +1 to the standards discussion above. I think one of difficulties in coming up with shared standards is that some issues have more than one valid position, so scoping the standards at the project level and documenting/enforcing them internally with ESLint (and possibly other things like .editorconfig files) seems like a good solution.

**Comment by anselmbradford** [comment]
I think if Jenkins/Travis failed on errors in the ESLint file, but not warnings (I suspect that'd be the default behavior anyway?), we can put all the absolute essential do-not-dos at error level and all the stylistic stuff at warning level. Cfgov-refresh now has this comprehensive [ESLint file](https://github.com/cfpb/cfgov-refresh/blob/flapjack/_settings/eslint.yaml) where I went through all the settings and explicitly laid them all out. It's a mixture of existing coding standards in the project and what made sense to do (based on browser compatibility concerns, etc.).

**Comment by wpears** [comment]
@anselmbradford nice work on that ans!

I'm parsing through it, but so far, so good!

**Comment by anselmbradford** [comment]
Also, not saying that has to be the CFPB standard ESLint file, but can be a starting point for seeing what can and can't be linted. The settings chosen were what made sense for cfgov-refresh.

**Comment by anselmbradford** [comment]
Per @virginiacc comment, here's an example [.editorconfig](https://github.com/cfpb/hmda-pilot/blob/master/.editorconfig) file in an existing project.

**Comment by ascott1** [comment]
Have you all seen https://github.com/feross/standard? It seems to be getting a lot of attention lately. I'm not crazy about omitting semicolons, but otherwise it's pretttty interesting.

**Comment by anselmbradford** [comment]
@ascott1 Yeah, takes care of the badge idea lol :smile: 

I wonder what they do with "`No unused variables – this one catches tons of bugs!`". I didn't like how JSHint handled that. It would count unused method parameters as unused variables (at least in the implementation I was using). IMO it's helpful code documentation to have unused parameters so you know if a method is receiving an argument from an event, for example. E.g.:

```javascript
btn.addEventListener('click', handleClick, false);
function handleClick(evt) {
   // evt event isn't used, but nice to know it's being added!
}
```

ESLint has a nice happy medium for allowing some unused parameters for exactly this case.

**Comment by ascott1** [comment]
Oh, that's interesting @anselmbradford. I hadn't considered that. I *think* for our purposes a simple custom ESLint file with an associated grunt task makes the most sense (unless we're all ready to abandon semicolons).

**Comment by ascott1** [comment]
I came across this guide over the weekend, which I really like the simplicity of: <https://github.com/bevacqua/js/blob/master/README.md>

**Comment by ascott1** [comment]
Now that the initial standard is in the master branch, let's close this issue and move further discussion and edits to new issues.
