### ISSUE TITLE
Path to 1.0 for this guide

### ISSUE THREAD

**Issue by ascott1** [cfpb/front-end#41]
Talking to @virtix, he asked me to consider what "1.0" looks like for this guide. Honestly, I think we're pretty close, but here's what I'd like to see:

- [x] **A testing guide** @imuchnik and @contolini have been doing  a lot of work to guide us towards a culture of testing. @anselmbradford has done a lot of research in visual/CSS testing. Let's document that!
- [x] **Revisit the CSS/Less guide** as it's basically my fork of another guide. What are we missing? Does it represent how we work?
- [ ] **Some recommended libraries** This might be treading in dangerous waters, but it also might be nice to say "in general we use _ for charts" etc.

What else could or should be included here?

**Comment by jimmynotjim** [comment]
I'd like to complete the Schema guide, but I don't know when I'll have the time so that can definitely wait till later if no one objects.

**Comment by contolini** [comment]
I'll draft something up for the testing section in the next couple days.

**Comment by ascott1** [comment]
@vitrix recommended that we document project structure. `generator-cf` spits that out, so it may be as simple as writing that down.

**Comment by contolini** [comment]
What is there to document about the project structure? The directories and files it generates?

**Comment by ascott1** [comment]
Yeah, I think that's what he meant

**Comment by virtix** [comment]
My thought is that articulating the _convention_ of the structure would be helpful; e.g.:

```
|-- app/
|----- assets/
|----------- img/      
|----------- css/    
|----------- js/      
|---- libs/
|---- dist/
|---- test/
|------- fixtures/
|--------------- data.json 
```

**Comment by ascott1** [comment]
Thanks for clarifying @virtix!

For transparency, the team met earlier in the week and discussed the following:

- @Scotchester is going to do a once over of the CSS style guide
- We created issue #46 to catalog the individual libraries we use

I think that gets us close to 1.0 and as a team we can focus on moving CF along.

**Comment by ascott1** [comment]
Since this is a leaving, breathing document, do we need to concern ourselves with `1.0`? If so, do you think it's there yet? If not, what else should we accomplish first?

**Comment by ascott1** [comment]
We've tagged this as 1.0 and I think it hits the initial goals we were aiming for. We're going to review this all with @virtix today for feedback, but we can safely close this issue.
