### ISSUE TITLE
boot script

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/front-end#49]
So I was chatting with @contolini about frontendbuild.sh and there are two things to put out into the wider community:

1) In a future world where you can go to any CFPB project and run a single script to get the project dependencies and build the project, should that script be named `frontendbuild.sh` or something like `bootstrap.sh` or `setup.sh` so that one day when that script leaves the front-end land we can have a script that will still be called the same, but will also make sense in a project that didn't have a front-end.

2) Anyone have any thoughts/opinions/issues with a build script that:
  - a) clears project dependencies.
  - b) installs project dependencies.
  - c) runs project configuration (such as grunt build).
Such a script might look like: https://gist.github.com/anselmbradford/1b87ecfda21325bb37dc

**Comment by imuchnik** [comment]
:+1:

**Comment by Scotchester** [comment]
1. I like `setup.sh`.
2. Makes sense to me. One note on your WIP script: generator-cf's Gruntfile, as currently constituted, requires the use of `grunt compile-cf` before `grunt build`.

**Comment by anselmbradford** [comment]
1. +1 for `setup.sh`
2. Good to note!

**Comment by contolini** [comment]
:+1:

Another improvement for your script: The Bower components' dir can be read from `.bowerrc` so I would add something like https://gist.github.com/contolini/4c9fe0238c1d789e2697#file-gistfile1-sh-L10-L19

**Comment by anselmbradford** [comment]
Niiiice ... maybe to future-proof it a little more so projects can know to put whatever config they need in an init function:
https://gist.github.com/anselmbradford/1b87ecfda21325bb37dc

**Comment by ascott1** [comment]
Discussed in meeting 7/17. Let's add documentation on using `setup.sh` and add it to the cf-generator.

**Comment by jimmynotjim** [comment]
Generator PR -> https://github.com/cfpb/generator-cf/pull/87

**Comment by anselmbradford** [comment]
Small adjustment... but realized the script should actually probably have a `clean` task instead of `clear`, to align it better with the conventions of grunt, gulp, etc. Updated --> https://gist.github.com/anselmbradford/1b87ecfda21325bb37dc

**Comment by anselmbradford** [comment]
Added ` --config.interactive=false` to https://gist.github.com/anselmbradford/1b87ecfda21325bb37dc per https://github.com/cfpb/cfgov-refresh/pull/810

**Comment by jimmynotjim** [comment]
C'mon dude, I just updated the PR ;)

Updated again.

**Comment by ascott1** [comment]
This is now in the generator and most projects are using a build script. Nice work y'all!

**Comment by anselmbradford** [comment]
Update to shrink picking out the bower directory from bowerrc to one line. Also adds output for npm directory location: https://gist.github.com/anselmbradford/1b87ecfda21325bb37dc
