### ISSUE TITLE
Project file structure

### ISSUE THREAD

**Issue by imuchnik** [cfpb/front-end#55]
I have noticed a strong affinity to putting everything in app.js or main.js. While it keeps things tidy and intuitively in one place, it does very little for project clarity. How does everyone feel about arriving at some more standardized project structure and smaller, well named files?

**Comment by ascott1** [comment]
In a lot of cases the `main.js` or `app.js` file is a bundled file from all of our modules. I do think we should have some sort of naming convention. For eRegulations we bundle everything into `regulations.js`. Should we start by auditing the current file production names?

Also, I think it would be really useful to have guidelines on structuring the modules in our projects. Those can vary wildly from project to project and depending on the framework (or lack thereof).

**Comment by cfarm** [comment]
yes to better file structure! I like a modules/plugins/libraries folder structure:

```
/js/
  /js/libraries/
  /js/modules/
  /js/plugins/
```

for file names, either camelCase or hyphen separated but it should be consistent.

**Comment by Scotchester** [comment]
n00b question: What is the difference between libraries, modules, and plugins?

**Comment by imuchnik** [comment]
If you chose a framework for your project, stay within it conventions. Otherwise, do something stupid obvious, like @cfarm example above or even simpler
```
/js/
  source/
  test/
  third-party/
```
Avoid deep nested structures or overly vague and overused names- e.g -'static'.

**Comment by ascott1** [comment]
We seem to have, mostly, settled on the file structure that the [generator](https://github.com/cfpb/generator-cf) produces. Does this need to be documented further?

**Comment by KimberlyMunoz** [comment]
I just added a quick note to the Readme to better introduce the generator. I think it's a nice addition for FEWDs, but that anything more than that can become outdated or redundant.

**Comment by ascott1** [comment]
:+1: Perfect, thanks @KimberlyMunoz!
