### ISSUE TITLE
Should we start using gulp?

### ISSUE THREAD

**Issue by ascott1** [cfpb/front-end#56]
When the first round of fellows joined the team Grunt was introduced to the front-end build process. Grunt is great and has allowed us to do lots of things (minifying files, optimizing images, bundling js modules, etc.). When gulp started to gain traction we decided that we shouldn't chase the shiny and instead should stick with the more mature task runner.

Now that gulp is reasonably mature and seems to have gained the majority of the market share (and is used by large organizations like Google and Facebook), should we consider switching going forward? What would that look like? Do existing projects continue to use grunt, but new projects have the option to use gulp?

![](http://hosting.tk-lee.com/tklee/funnies/SZMZM42.jpg)

**Comment by awolfe76** [comment]
Is there a benefit to Gulp over Grunt? Not against it, just haven't used Gulp at all so curious about what it would offer. Performance benefits? Others?

**Comment by ascott1** [comment]
I think these two links do a good job of summing it up @awolfe76:

- <https://medium.com/@preslavrachev/gulp-vs-grunt-why-one-why-the-other-f5d3b398edc4>
- <http://markdalgleish.github.io/presentation-build-wars-gulp-vs-grunt/>

**Comment by awolfe76** [comment]
:smiley: Just read through those and it sounds good to me! Maybe we can start some test runs here and there to see how it plays out? Wouldn't mind doing it on some of the projects I've been working on.

**Comment by mistergone** [comment]
My entire opinion: I don't know. I don't know grunt. I don't know gulp. I don't like complicated build processes, so simplicity is all I ask for. That is all! :smile: :space_invader: :dancer: :rocket:

**Comment by jimmynotjim** [comment]
I'd argue if you are comfortable with writing JS, Gulp is the simpler of the two.

**Comment by awolfe76** [comment]
> I don't like complicated build processes, so simplicity is all I ask for. :+1:

**Comment by cfarm** [comment]
No. I think we have real problems to solve and spend our time on (accessibility, Capital Framework) and this would detract from those efforts.

**Comment by ascott1** [comment]
> No. I think we have real problems to solve and spend our time on (accessibility, Capital Framework) and this would detract from those efforts.

My thinking is that by taking some of the pain of configuring grunt out of the mix, this could help us spend more time on those problems.

**Comment by ascott1** [comment]
Also, it's worth noting that a few projects have gone rogue and used gulp. This would welcome them into the fold with open arms and a `frontendbuild.sh` script.

**Comment by cfarm** [comment]
Fair enough. I guess I haven't really run into any problems configuring Grunt on owning a home since it was mostly done (by you, @ascott1!) before I started. If it's solving a specific time consuming problem on a new project that makes sense. I just didn't get that from the question as posed here.

Also my attitude is 1000% influenced at this moment by a talk I'm watching from Lyza Gardner about overchoice in web development with this excellent quote:

> Constraints allow us to innovate in areas that matter.

I just hope we can achieve that last part :)

**Comment by ascott1** [comment]
> If it's solving a specific time consuming problem on a new project that makes sense. I just didn't get that from the question as posed here.

Sorry, yeah. This started with a chat conversation that I thought was better moved into the public, so I'm sure a lot of the context got lost along the way. 

On a personal level, my main gripe with Grunt is that it can be pretty slow for codebases that contain a lot of JavaScript. Working with Gulp on a side project that uses React really caused me to notice the speed advantage.

All of that said, I completely agree with your point. Build tools should take the pain points out of web development, not introduce new ones and certainly not be a time sink.

And that's a great quote. I do think that we do amazing, constraint bound, and innovative work here, but there's always room to grow and do it better.

**Comment by wpears** [comment]
I think this decision is small enough to be determined on a team-by-team basis. What an organization gains from strict adherence (everybody use grunt!) is mostly ease of switching teams and speed on starting new projects. In this case, grunt and gulp are similar enough that I doubt it would cause too much trouble for a new member of the team. Also, build processes tend to not be too fluid, so it isn't like someone is going to be added to a team then expected to muck with a constantly changing gulpfile with no experience.

If a team wants to use gulp because they think it will improve their development process, go for it. Do it well, share your experience, and get back to the problem your team is working to solve.

**Comment by mistergone** [comment]
> Constraints allow us to innovate in areas that matter.

I may tattoo this on my forehead. Except I'd say, "Constraints force us to learn." I still think about people using lynx when I'm coding, and I don't even think that's a thing any more. But I almost feel like the more stuff we add, the more constrained we become... but that's a different discussion.

To make this comment relevant, "What Wyatt said is interesting. Could this be project-level?"

**Comment by ascott1** [comment]
> "What Wyatt said is interesting. Could this be project-level?"

I think so, as long as we all adhere to having a single front-end build script, like [Owning a Home](https://github.com/cfpb/owning-a-home/blob/master/frontendbuild.sh).

My biggest fear here is that we introduce a bunch of tools that need to be installed (and keep updated or have even have different versions running) on servers to support different projects. 


So... maybe I should've ignored the fact that this seemed like a fun Friday debate and kept my big mouth :no_mouth:

**Comment by cfarm** [comment]
@ascott1 you opened this can of worms and you're gonna deal with the consequences!!!

Actually now I wanna use gulp with react and see how fast it is..

**Comment by ascott1** [comment]
Discussed in a meeting 7/17. We're sticking with Grunt(for now). Closing!

**Comment by jimmynotjim** [comment]
We finally ran into a few walls with Grunt (issues with timing of tests, running protractor, and the inability to get any of the "changed/newer" plugins working) so we made the initiative to explore and compare it with Gulp. Turns out it's a lot better

https://github.com/cfpb/cfgov-refresh/pull/797

Luckily these worms are very tasty

![fruit_gummy_worms](https://cloud.githubusercontent.com/assets/1280430/8968894/28fa647a-360e-11e5-8b1d-255ceb56363e.gif)

**Comment by KimberlyMunoz** [comment]
What would folks think about adding gulp to generator?

Another project using gulp:
https://github.com/cfpb/dash/blob/master/gulpfile.js

**Comment by marcesher** [comment]
Intruder alert, Intruder alert, BEWD in the front-end house.

I've been using gulp on a personal project and quite like it.

From a consistency perspective for build/deploy, I think the team's decision to have a `frontendbuild.sh` script effectively abstracts the implementation details of the build. This way, for Jenkins, if it's grunt, or gulp, it doesn't matter.

**Comment by ascott1** [comment]
> From a consistency perspective for build/deploy, I think the team's decision to have a frontendbuild.sh script effectively abstracts the implementation details of the build. This way, for Jenkins, if it's grunt, or gulp, it doesn't matter.

:heart_eyes: 

This is a great point @marcesher. Perhaps the next major step for this would be to modify generator-cf so that users have a choice between grunt and gulp.

**Comment by Scotchester** [comment]
> Perhaps the next major step for this would be to modify generator-cf so that users have a choice between grunt and gulp.

This idea was actually suggested in the meeting on Friday! I think that might be what Kimberly meant by her question, which was posted during or right after the meeting.

**Comment by ascott1** [comment]
> This idea was actually suggested in the meeting on Friday! I think that might be what Kimberly meant by her question, which was posted during or right after the meeting.

Amazing! I :heart: this team. :boom:

**Comment by jimmynotjim** [comment]
If no one objects, I'll take this on. I've implemented the same Grunt/Gulp choice in the WP Evolved generator so it won't be difficult to do the same to the CF generator.

**Comment by ascott1** [comment]
No objections on this end!

**Comment by contolini** [comment]
Closing in favor of https://github.com/cfpb/generator-cf/issues/91
