### ISSUE TITLE
Less vs Sass vs ?

### ISSUE THREAD

**Issue by awolfe76** [cfpb/front-end#57]
After seeing #56 I thought I would bring this up.

There are plenty of [articles debating this](https://www.google.com/search?q=less+vs+sass&ie=utf-8&oe=utf-8&aq=t&rls=org.mozilla:en-US:official&client=firefox-a&channel=sb).

Some of the same problems from the Grunt vs Gulp issue come up here:
- How would a change happen?
  - New projects can use Sass, switch older projects as time allows?
- Rebuild CF? (I heard Bootstrap is doing this.)
- Have both available as long as the remain relatively the same according to the design manual
  - To me the design manual is the driver here and as long as a site/app meets it we're good
- There are plenty of new players here too (postcss, cssnext, etc)

Full disclosure:
- I prefer Sass (node-sass)
- I have been using it to prototype several projects for HMDA 

Let the :fireworks: begin.

**Comment by Scotchester** [comment]
Notes on this from our internal Dev Manual's Core Technologies page (<http://[ghe]/pages/CFPB/dev-manual/core-tech.html>):

> Context: Introduced to the Bureau on the Intranet in early 2012 by way of using Bootstrap as the initial framework for the Intranet. When first round of fellows arrived, the FEWD team held a discussion on which CSS preprocessor to adopt as our standard (if any). Less was chosen due to existing familiarity and ease of adoption (because it’s closer to standard CSS than Sass). [This post by the co-creator of Bootstrap](http://www.wordsbyf.at/2012/03/08/why-less/) influenced our thinking greatly.

**Comment by awolfe76** [comment]
Makes perfect sense.

Bootstrap is going the Sass (scss) route for their v4 release, and possibly postcss for v5.
The scss pattern, which I think most people use, is very similar to CSS and very easy to learn.
Sass also, maybe not at the time Less was chosen, seems to have gathered the majority of the community support.

[Node-sass is fast.](http://www.solitr.com/blog/2014/01/css-preprocessor-benchmark/)

**Comment by jimmynotjim** [comment]
Agreed on the reasons for using Sass. I still far prefer it over Less for many reasons, least of which is separating classes and mixins, as well as defining custom functions and silent placeholders. I've tried using Less's extend, but it's really not intuitive at all.

I think conversion right now is far more work than converting from Grunt to Gulp. If something like PostCSS is in the future, I'd be hesitant to switch to Sass now. BS has had a Sass fork for a few years, so it's a bit easier for them to move away from Less now than it would be for us. That said, I still don't know enough about PostCSS to know if it's even a possibility for our future.

**Comment by ascott1** [comment]
At this point, we're pretty well invested in Less. I can see many very reasonable arguments in favor of Sass, but I don't think they're compelling enough for us to take on the burden of making the switch.

I do think @jimmynotjim brings up a good point about [PostCSS](https://github.com/postcss), which seems like the sort of thing we should be exploring long-term.

Thanks for opening up this issue @awolfe76! I'm going to close it for now, but it's always good to keep these discussions going.
