### ISSUE TITLE
How do we test React components?

### ISSUE THREAD

**Issue by ascott1** [cfpb/front-end#58]
@imuchnik brought up a really interesting discussion today on trying to test React components for Owning a Home. This is something that we should explore a bit, as it seems to be a friction point. Specifically testing React components with Browserify.

## Current state

DevDash is using React and testing with [Jest](https://facebook.github.io/jest/), but @contolini strongly suggested we don't do that.

Owning a Home uses Mocha/Chai/Sinon for testing and @imuchnik and @amymok were writing tests for the React components with this setup.

## Open questions

Let's try to answer the following:

- What are the current pain points/known issues with testing React components?
- What is our desired workflow for testing React components?

Based on those two questions, let's then explore how other projects test React and hopefully find something that works well for us.

cc: @imuchnik @contolini @cfarm @virginiacc @amymok

**Comment by imuchnik** [comment]
Have we decided to use React going forward? I would strongly advise against bringing react into existing applications, UNLESS we make a commitment to port everything to React over time. 

Also, would strongly advise agains using Fluxx. I am looking into other alternatives right now for devdash. 

@cfarm @virginiacc @contolini @dgreisen-cfpb @amymok @ascott1 Please chime in.

**Comment by ascott1** [comment]
@imuchnik to answer your question:

We explored using React in one production application. At this time there aren't plans to use React in any upcoming tools. Let's revisit this if needed.
