### ISSUE TITLE
Overall front-end guide

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/front-end#6]
North is a living standard for project development and may serve as a good starting point for a front-end guide (maybe even would be worthwhile using it directly):

https://github.com/north 
https://github.com/north/north

**Comment by anselmbradford** [comment]
Per discussion on 3/16... JS, markup, CSS/Less teams should create a markup doc in a branch.

- [ ] JS doc.
- [x] [markup doc](https://github.com/cfpb/front-end/blob/team-markup/markup.md).
- [ ] CSS/Less doc.

**Comment by ascott1** [comment]
Should this be a Jekyll site or just a collection of markdown files in the repo with a table of contents in the README?

**Comment by KimberlyMunoz** [comment]
I'm leaning towards the second. I think it accomplishes the same thing with much less work.

**Comment by jimmynotjim** [comment]
Ditto, the thoughbot Guides I linked to before work this way and I agree it's much easier to maintain.

**Comment by awolfe76** [comment]
I like the README idea too. Still possible to generate a front-end for it too, if we need to. 
(I'm assuming north/north is doing something similar.)

**Comment by anselmbradford** [comment]
Since everything's in as markdown files in this repo, I think this can be closed.
