### ISSUE TITLE
Consumer complaint API workshopper?

### ISSUE THREAD

**Issue by ascott1** [cfpb/front-end#65]
@contolini and I very briefly talked about this a long time ago...

Wouldn't it be cool if we developed a nodeschool style [workshopper](https://github.com/workshopper/workshopper) for working with the consumer complaint database?

I'm not really sure what that would look like, but let's talk about it here! I'm volunteering to work on this, but I'd like to collaborate with someone on it.

For some inspiration, 18F used the CCDB [for a data visualization workshop](http://openglobe.github.io/cfpb-dataviz/)

**Comment by contolini** [comment]
We should check in with @OpenGlobe and @ErieMeyer before writing the curriculum. I'm curious how the workshop went.

**Comment by ErieMeyer** [comment]
Very happy to help!

**Comment by ascott1** [comment]
Closing, though this would be a great project for CFPB's hack day!
