### ISSUE TITLE
What does your grunt do?

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/front-end#69]
Hey all,

We had an issue earlier where we discussed [grunt tasks](https://github.com/cfpb/cfgov-refresh/pull/779#issuecomment-125680175) and saw there wasn't really any uniformity in what grunt tasks did what.

This is what @anselmbradford has found from other projects.:
> I browsed through some other projects to see what they did around their building tasks. Owning-a-home has build, release, ship, and deploy tasks that are related to building and releasing steps. Eregs uses test, test-js, build, squish. Dash uses build and test, with a default of those two run together (like what Jimmy mentioned). Sentia uses test, testServerSide, frontEndTest, frontAndServerSideTest, and build, which runs the frontAndServerSideTest task. So... the short of it is there's no real cfpb standard that I can see.

Right now this is what Flapjack has
- `grunt build` - cs, js tasks
- `grunt test` - unit, macro tests
- `grunt` - build and test

Does anyone have any strong thoughts on what grunt tasks should do what for front-end projects or if it makes sense to standardize the basic ones like `grunt` or `grunt build`?

**Comment by anselmbradford** [comment]
@jimmynotjim pointed out linting and some testing should happen on the source code, while some testing should happen on the production code. So a pipeline would look something like lint > test:unit (done on source code) > build > test:integration (done on production code)

**Comment by ascott1** [comment]
It's worth noting that in [Building Your Projects Front-End](https://github.com/cfpb/front-end/blob/master/build.md) we attempted to recommend guidelines around this:

>> Only require three commands to install dependencies and build all static assets:
* npm install
* bower install
* grunt build
These three commands (and any additional commands if there's a strong argument for them) should be stored in a setup.sh file to make things easier for our CI environments.

That doesn't make any recommendations about what other tasks should do or be named though.

**Comment by ascott1** [comment]
We've standardized on using the generated Gulp or Grunt file from generator-cf.
