### ISSUE TITLE
DalekJS

### ISSUE THREAD

**Issue by ascott1** [cfpb/front-end#7]
Selenium has been a barrier to entry for me for functional testing. I'm really interested in exploring the use of [DalekJs](http://dalekjs.com/).

This paragraph in particular resonates with me:

> The process we've been through made me think, how should such a tool represent itself to the developers, how can it be "a nobrainer" for web developers, for the people who build what you see in the internetz, the frontend devs, for everyone?! I came to the conclusion that only JavaScript can be considered as a "common knowledge programming language" in web land.
Also the setup process for running the tools that ran the Selenium tests (Java jrde*whatever, Maven, Ant, jUnit, Eclipse, etc.) was a major pain point in my opinion, I wan't it to be as easy as installing a tool via npm.

As an added bonus Dalek has a Grunt plugin and integrates with Saucelabs.

**Comment by ascott1** [comment]
Of course, there's also this:

> * DalekJS is currently a developer preview. Some features are missing, some things might change, there's a lot of optimisation to be done. Don't use this for production!

:pensive:

**Comment by mistergone** [comment]
I am very interested in this. And it's hard to say no to Daleks.

![Dalek party](https://31.media.tumblr.com/2d40a681634f83ffe359d326920be5b4/tumblr_inline_mr7x4zCKOL1qz4rgp.gif)

**Comment by sephcoster** [comment]
Would this replace Jasmine / Mocha or be a test suite we'd run in addition to those? Seems like it has its own testing / assertion frameworks. I like the syntax and the install process is super easy, but am a bit nervous about the overall support given the disclaimer you posted above.
